-- Seed intencionalmente enxuto.
--
-- A partir da H5, o vínculo de profiles com auth.users passa a ser parte do
-- contrato do schema. Como ainda não conectamos os fluxos reais de auth ao app,
-- manter dados demo aqui só criaria usuários e memberships artificiais.
--
-- O baseline local agora nasce vazio e reproduzível:
-- 1. rode as migrations
-- 2. crie usuários reais quando a H7/H8 entrar
-- 3. crie grupos, convites, despesas e settlements pelos fluxos do app
